curl -X GET http://localhost:3000/allFactures

curl -X GET http://localhost:3000/allClient

curl -X GET http://localhost:3000/allVoiture

curl -X GET http://localhost:3000/allRole

curl -X GET http://localhost:3000/allEmploye

curl -X GET http://localhost:3000/client/1/factures